# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='torchat_id',
            field=models.CharField(default='no', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
