# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20160227_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='capture_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
